### ISSUE TITLE
Adding Header & Footer

### ISSUE THREAD

**Issue by Meet2054** [EbookFoundation/free-programming-books#9766] opened 2023-10-03 05:30 UTC
The website does not have a Header or Footer, I would love to work on creating a header and footer and am also willing to add background to the webpage.

**Comment by sanchalithareja** [comment] 2023-10-03 06:15
Hi sir, can I please be assigned this issue?

**Comment by mrunal12345-lab** [comment] 2023-10-03 06:27
hello sir ,can you assign this task to me?

**Comment by Vamiq01** [comment] 2023-10-03 08:37
Hi sir , can you please assign me this issue. i can make responsive header and footer.

**Comment by Gowrish7** [comment] 2023-10-03 08:49
> The website does not have a Header or Footer, I would love to work on creating a header and footer and am also willing to add background to the webpage.
Hey Meet can you specify any particular design to be implemented ?

**Comment by KhyathiKancharla** [comment] 2023-10-03 10:16
I checked the website in detail and I would like to work on creating the header and footer with a background colour which will be coordinated with the website colour palette. 

Please allow me to contribute 
![ebook](https://github.com/EbookFoundation/free-programming-books/assets/110332342/3f59e20d-5648-42a8-96ce-14c48067580d)

**Comment by Pratik1603** [comment] 2023-10-03 11:49
I would like to work on this issue

**Comment by ranixhirani** [comment] 2023-10-03 12:18
I'm proficient in HTML, CSS, and JavaScript and would love to contribute by designing the header and footer for your open-source repo. Let me know how I can assist!

**Comment by Mahe9041** [comment] 2023-10-03 12:21
I would like to contribute in this issue. Please assign it to me.

**Comment by eshellman** [comment] 2023-10-03 13:21
the website config is in https://github.com/EbookFoundation/ebookfoundation.github.io  please move discussion there

**Closed by eshellman** 2023-10-03 13:21 UTC
