### ISSUE TITLE
Is there an API available ?

### ISSUE THREAD

**Issue by AhmedElTabarani** [EbookFoundation/free-programming-books#6699] opened 2022-02-07 13:30 UTC
Is there an API available for this repo?

How would the API will be useful?
Imagine a person applying an application to display the courses and books available for each field Or while writing articles on a specific field that you want to witness the educational courses for this field, whether for any language 

It sure has other uses And look to the future and with the development of technology, this repository may literally be a repository of books and educational courses in the field of programming,  And it really is

**Comment by davorpa** [comment] 2022-02-07 14:56
Please see #6643

**Comment by davorpa** [comment] 2022-02-08 07:13
Duplicate of #5778

**Closed by davorpa** 2022-02-08 07:13 UTC
Labels: question
