### ISSUE TITLE
Broken Link in Cheat-sheets

### ISSUE THREAD

**Issue by Lyponellen** [EbookFoundation/free-programming-books#5342] opened 2021-04-22 10:24 UTC
C++ Cheat sheet not available.

https://www.cs.ccu.edu.tw/~damon/oop/,c++refcard.pdf
https://person.dibris.unige.it/moggi-eugenio/PG1-13/Cpp_reference.pdf
one of them could be an alternative

**Comment by eshellman** [comment] 2021-04-24 17:37
Dead links should be removed. The 2 links you suggest are good content, but casually posted, not clear if the poster has permission to distribute. In other words, the sort of links that go bad within a year, so not the best for our purposes.

**Comment by davorpa** [comment] 2021-07-12 15:35
Duplicate of #5378

**Closed** 2021-07-12 15:53 UTC
Labels: PR requested
