### ISSUE TITLE
Adding resources for Jenkins in Devops

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [EbookFoundation/free-programming-books#10031] opened 2023-10-09 05:05 UTC
@eshellman can you assign me this issue under hacktoberfest 2023

**Comment by sohansai** [comment] 2023-10-09 14:16
If you're familiar with Git, please feel free to submit a PR.

If not, provide details about the book, including its name, author, and a link to it.

Note that issues can't be assigned, but if you're ready, you can start contributing right away.

Also, make sure to read CONTRIBUTING.md before contributing.

**Comment by ngv-sama** [comment] 2023-10-11 09:40
Hi! I am new to open source. Can someone please help me with what the issue is?
Thanks!

**Comment by AbdulSami455** [comment] 2023-10-12 13:17
Assign this to me as I'm interested in DevOps and have knowledge of jenkins.

**Closed** 2023-11-22 01:14 UTC
